### ISSUE TITLE
lp Print Options

### ISSUE THREAD

**Issue by semery22** [jenkstom/iSeriesPDF#2]
Hey,
I am testing your program. 
I went to know if your program create the PDF file with lp print options ?

Exemple: 
lp -o orientation-requested=5 cds.txt
 lp -o landscape  cds.txt

Thank you

**Comment by jenkstom** [comment]
No, it uses ghostscript as a command-line tool. So for landscape you could use something like:

-dAutoRotatePages=/PageByPage

or

-c "<</Orientation 3>> setpagedevice"

Which you would put in or near line 538 of the lpd.cs file. Please see the [ghostscript documentation](https://www.ghostscript.com/doc/9.27/Use.htm) for more info.

**Comment by semery22** [comment]
Thank you!
